// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF-UOpISffltRenbOxrLBAYliJ_IraX1Y',
    appId: '1:704821362133:web:f22a240410153585b2915c',
    messagingSenderId: '704821362133',
    projectId: 'food-delivery-app-55433',
    authDomain: 'food-delivery-app-55433.firebaseapp.com',
    storageBucket: 'food-delivery-app-55433.appspot.com',
    measurementId: 'G-QR09WGMPJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rEUkVKTq-r2pQDI_aYzuBjLjW-Dbp1U',
    appId: '1:704821362133:android:edf85be436228abfb2915c',
    messagingSenderId: '704821362133',
    projectId: 'food-delivery-app-55433',
    storageBucket: 'food-delivery-app-55433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI-KpSq6TvhLAK1XGysjmlZrMTyBdwS7E',
    appId: '1:704821362133:ios:3a0c30d185839bdfb2915c',
    messagingSenderId: '704821362133',
    projectId: 'food-delivery-app-55433',
    storageBucket: 'food-delivery-app-55433.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI-KpSq6TvhLAK1XGysjmlZrMTyBdwS7E',
    appId: '1:704821362133:ios:fb0dac1a2f7f7ec7b2915c',
    messagingSenderId: '704821362133',
    projectId: 'food-delivery-app-55433',
    storageBucket: 'food-delivery-app-55433.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
